### ISSUE TITLE
Fel i checksumman

### ISSUE THREAD

**Issue by deberman** [epkboan/rain_sensor#1]
Jag fick inte detta att fungera med min tellstick-net så jag tog en litet titt i koden och tror det är en bugg när checksumman sätts. Rad 92 i osv3_pcr800.cpp

```
//m_packet[13]   = (checksum << 4) & 0xF0;  // orginal funkar ej med tellstick-net
  m_packet[13] = checksum & 0xF0;              // Verifierad fungerar med tellstick-net
```

Tack för koden annars! Har precis kommit igång med att göra egna sensorer till tellsticken.

**Comment by boanjo** [comment]
Ah, ja det blev verkligen bara nonsens som sista nibble. Bra tack, fixat!

Anledningen att det smet under radarn var att jag slutade använda tellstick innan jag började göra egna sensorer. Min txrx kollade bara den första nibblen (pga av något problem med crc checksumman på någon tidig Oregon temp mätare eller vad det nu var.

**Comment by deberman** [comment]
Jag har precis suttit och gjort ett arduino bibliotek av koden. Gjorde även en variant av den fast vindmätare WGR800.
Den enda copyright  notisen är den som hänvisar till Jack Christensen. Jag har lagt in den i filerna men vill du att jag pekar hit också? Jag är inte så hemma på sånt här.

**Comment by boanjo** [comment]
Det får du göra som du vill för min del. Kul att det inspirerar till kreativitet bara!
