### ISSUE TITLE
atmega baseboard

### ISSUE THREAD

**Issue by karioja** [epkboan/rain_sensor#2]
What is the atmega baseboard you're using for this? I have these http://www.spikenzielabs.com/SpikenzieLabs/sippino.html but you're board seems to have a convenient i2c header and an option to mount a voltage regulator. I tried zooming in on the picture to read the text but googling for www.ldwlcel.se does not bring any hits. ;)

Och samma på svenska.

**Comment by boanjo** [comment]
Hi

It says in the text "from the swedish company Lawicel" https://github.com/epkboan/rain_sensor but here is a direct link :)

https://www.lawicel-shop.se/catalogsearch/result/?q=+BRAGE-SIP-LT

BR
//Anders
